### PR TITLE
Added script in root directory

### PR DESCRIPTION
**Pull request by pranavmadhu01**
now we can use **npm run frontend** and **npm run backend** in the root directory to start the project rather than cding in to both seperately

### CODE REVIEW

**Review by agnivg — COMMENTED** [review]
Don't write this script as of now, let the backend get completed then write it

**Comment by s-shubham-22** [comment]
> now we can use **npm run frontend** and **npm run backend** in the root directory to start the project rather than cding in to both seperately

Pranav are you working on frontend?

**Comment by pranavmadhu01** [comment]
> > now we can use **npm run frontend** and **npm run backend** in the root directory to start the project rather than cding in to both seperately
> 
> Pranav are you working on frontend?

yes @s-shubham-22

**Comment by pranavmadhu01** [comment]
> Don't write this script as of now, let the backend get completed then write it

ok

**Comment by s-shubham-22** [comment]
Pranav Create the react app with CRA, or is there any other approach you are using?

**Comment by pranavmadhu01** [comment]
A s of now the app is created with CRA.

> Pranav Create the react app with CRA, or is there any other approach you are using?

currently CRA is used.

**Comment by s-shubham-22** [comment]
@pranavmadhu01 can you please commit, push and create PR of the updated React App which you have created with CRA?

**Review by agnivg — COMMENTED** [review]
Thinking of merging it as some part of back-end is done, can you resolve this merge conflict issue.
@pranavmadhu01

**Comment by pranavmadhu01** [comment]
> Thinking of merging it as some part of back-end is done, can you resolve this merge conflict issue. @pranavmadhu01

sure

**Comment by pranavmadhu01** [comment]
resolved the conflicts @agnivg

**Comment by pranavmadhu01** [comment]
> @pranavmadhu01 can you please commit, push and create PR of the updated React App which you have created with CRA?

This is ok ig

**Review by agnivg — APPROVED** [review]
Yes, everything's fine

**Pull request merged**
