### PR TITLE
Basic structure of the todo Dashboard created

### PR DESCRIPTION
**Pull request by pranavmadhu01**
image

### CODE REVIEW

**Comment by pranavmadhu01** [comment]
@agnivg

**Review by agnivg — COMMENTED** [review]
Remove the what is your new task input box, as multiple things are needed to be taken as input, so only keep the button Add ToDo such that on clicking it, a modal will open and then input will be given there

**Comment by pranavmadhu01** [comment]
> Remove the what is your new task input box, as multiple things are needed to be taken as input, so only keep the button Add ToDo such that on clicking it, a modal will open and then input will be given there

sure

**Comment by pranavmadhu01** [comment]
image

**Comment by agnivg** [comment]
Closing this pull request, as UI will look completely different, as designed by prakhar

**Pull request closed without merging**
