### PR TITLE
login signup:login signup component created with basic design

### PR DESCRIPTION
**Pull request by pranavmadhu01**
Screenshot from 2023-01-23 21-16-41
Screenshot from 2023-01-23 21-16-47

### CODE REVIEW

**Review by agnivg — COMMENTED** [review]
You can add a heading with "To-Do List" and also add a subheading with "Login/Signup", also add some padding in the login/signup div. Also center the login and signup button

**Comment by pranavmadhu01** [comment]
image
image

**Comment by pranavmadhu01** [comment]
@agnivg

**Review by agnivg — COMMENTED** [review]
Remove the green background and keep it white as of now, also instead of TO DO LIST heading write Login/Signup as heading, also increase the margin top for the green button (login/signup), rest is okay. Make these changes and I will merge it then

**Comment by pranavmadhu01** [comment]
image
image
@agnivg

**Review by agnivg — COMMENTED** [review]
Looks okay as of now, in the next commit do include the navbar created by @AmazingAryan  and in the login page, make the button in the centre, it has gone to the bottom

**Comment by pranavmadhu01** [comment]
> Looks okay as of now, in the next commit do include the navbar created by @AmazingAryan and in the login page, make the button in the centre, it has gone to the bottom

The login and signup page can be navigated in the block itself so is the nav-bar really needed

**Comment by agnivg** [comment]
Some more tabs will be included in the navbar in later stage othar than home and signup/login, so add it as of now, but yes some of them will need authentication to access them

**Comment by pranavmadhu01** [comment]
image

**Comment by pranavmadhu01** [comment]
image
@agnivg

**Review by agnivg — APPROVED** [review]
Everything's okay

**Pull request merged**
