### PR TITLE
Login Route Created

### PR DESCRIPTION
**Pull request by s-shubham-22**

### CODE REVIEW

**Review by agnivg — COMMENTED** [review]
Seems alright to me, but why have you used passport instead of jwt token, Any reason behind it?

**Comment by s-shubham-22** [comment]
Nothing specific
If you want in passport js then that's also fine by me

**Review by agnivg — APPROVED** [review]
No issues, it's fine , I was just asking if it is more secure or not

**Comment by s-shubham-22** [comment]
@agnivg I've created login and registration system with session facility using passport JS. So should I change it and commit it and push it? Because it is well structured compared to JWT

**Comment by agnivg** [comment]
Your code is well written, no need to change it, I have merged your code too

**Pull request merged**
