### PR TITLE
User Registration Route Completed

### PR DESCRIPTION
**Pull request by s-shubham-22**
The user Registration Route has been completed. Some minor changes are remaining in it Like Proper response, etc. But I'll update that in the next commit. Have also worked on user login API a bit, but it's still in progress.

### CODE REVIEW

**Review by agnivg — COMMENTED** [review]
why are you saving the salt in database, you can use salt value 10 for all passwords, saving salt in database is not a good thing.

**Comment by s-shubham-22** [comment]
Okay I'll update it and create a PR.
Thank you for the better suggestion 👍🏻

**Comment by s-shubham-22** [comment]
I've Changed the salt from dynamic to static (value is 10) and committed the changes, You can review the code. If any changes are required then pls comment down here. Thank you

**Comment by agnivg** [comment]
Everything seems fine to me, just tell me one thing have you tested the api's using postman or any other api testing application?

**Comment by s-shubham-22** [comment]
Yeah, The register route is complete with validations of inputs at backend and I've tested it using thunder client in VS Code

**Review by agnivg — APPROVED** [review]

**Pull request merged**
